### PR TITLE
Fix build with libcxx 20.1.8

### PR DESCRIPTION
**Pull request by 4JustMe4**
This include is required for realpath since libcxx about version 20.1.8.
```
/root/efsw/src/efsw/FileSystem.cpp:148:2: error: use of undeclared identifier 'realpath'
  148 |         realpath( path.c_str(), &dir[0] );
      |         ^
1 error generated.
```

### CODE REVIEW

**Comment by SpartanJ** [comment]
Thanks!
